[project]
name = "crewdemo"
version = "0.1.0"
description = "crewDemo using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.12.2"
]

[project.scripts]
crewdemo = "crewdemo.main:run"
run_crew = "crewdemo.main:run"
train = "crewdemo.main:train"
replay = "crewdemo.main:replay"
test = "crewdemo.main:test"
run_with_trigger = "crewdemo.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
